language: python
python:
  - 2.6
  - 2.7
  - 3.2
install: 
  - pip install -e git://github.com/ptahproject/ptahcrowd.git
  - python setup.py develop
script: python setup.py test
notifications:
  irc: "irc.freenode.org#ptahproject"
