language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install git+http@github.com:ptahproject/ptah
  - python setup.py develop --allow-hosts='pypi.python.org'

script: python setup.py test

notifications:
  irc: "irc.freenode.org#ptahproject"
